# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Staging CI/CD Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - staging

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - name: Setup project before build
        run: npm install

  build:
    runs-on: ubuntu-latest
    environment: staging
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Install package
        run: npm install --silent
      - name: Building the project first
        run: npm run build --if-present

  deployment:
    runs-on: ubuntu-latest
    environment: staging
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }}
